
landmarks = {
'Changi Airport': set(['Changi Airport']),
'Esplanade': set(['Esplanade']),
'Gardens by the Bay': set(['Bayfront']),
'Singapore Art Museum': set(['Bras Basah', 'Bencoolen']),
'Science Centre': set(['Jurong East']),
'Jurong Bird Park': set(['Boon Lay']),
'Singapore Zoo': set(['Ang Mo Kio', 'Khatib']),
'National University of Singapore': set(['Kent Ridge', 'Clementi', 'Buona Vista']),
'National Technological University': set(['Pioneer', 'Boon Lay']),
'Fort Canning Park': set(['Dhoby Ghaut', 'Bencoolen']),
'CHIJMES': set(['Bras Basah', 'City Hall']),
'Singapore River': set(['Clarke Quay']),
'Merlion Park': set(['Raffles Place']),
'Chinatown': set(['Chinatown', 'Outram Park']),
'Little India': set(['Little India']),
'Singapore Discovery Centre': set(['Joo Koon']),
'Raffles Institution': set(['Marymount', 'Bishan']),
'West Coast Park': set(['Haw Par Villa', 'Clementi']),
'East Coast Park': set(['Bedok']),
'Vivo City': set(['HarbourFront']),
'Lau Pa Sat': set(['Downtown', 'Telok Ayer']),
'Kampung Glam': set(['Bugis']),
'Suntec City': set(['Promenade', 'Esplanade']),
'Singapore Flyer': set(['Promenade']),
'Marina Bay Sands': set(['Marina Bay', 'Bayfront']),
'MacRitchie Nature Trail': set(['Marymount', 'Caldecott'])
}